input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { "message" => '%{IPORHOST:client_ip} - - \[%{HTTPDATE:timestamp}\] "%{WORD:http_method} %{URIPATHPARAM:request}"' }
  }
  date {
  match ==> ["timestamp", "dd/MM/yyyy:HH:mm:ss Z"]
  target => "@timestamp"
  }

  useragent {
    source => "user_agent"
    target => "user_agent_details"
  }
}

output {
  stdout {
    }
  elasticsearch {
    host => [ "elasticsearch:9200" ]
    index => "logs_app_gen-%{+YYYY.MM.dd}"
  }
}
