# This is a configuration file for Zabbix server daemon
# To get more information about Zabbix, visit https://www.zabbix.com

############ GENERAL PARAMETERS #################


### Option: LogFile

LogFile=/var/log/zabbix/zabbix_server.log

### Option: LogFileSize
LogFileSize=0

### Option: PidFile
PidFile=/run/zabbix/zabbix_server.pid

### Option: SocketDir
SocketDir=/run/zabbix

### Option: DBName
DBName=zabbix_base

### Option: DBUser
DBUser=zabbix

### Option: DBPassword
DBPassword=zabbix12345


############ ADVANCED PARAMETERS ################

### Option: SNMPTrapperFile
SNMPTrapperFile=/var/log/snmptrap/snmptrap.log

### Option: ListenIP
#       List of comma delimited IP addresses that the trapper should listen on.
#       Trapper will listen on all network interfaces if this parameter is missing.
#
# Mandatory: no
# Default:
ListenIP= 0.0.0.0


### Option: Timeout
Timeout=4

### Option: FpingLocation
FpingLocation=/usr/bin/fping

### Option: Fping6Location
Fping6Location=/usr/bin/fping6

### Option: LogSlowQueries
LogSlowQueries=3000

### Option: StatsAllowedIP
StatsAllowedIP=127.0.0.1,10.0.10.0/24,10.0.11.0/24

### Option: EnableGlobalScripts
EnableGlobalScripts=0

### Option: Include
Include=/etc/zabbix/zabbix_server.d/*.conf


