[bastion]
158.160.34.17

[zabbix]
10.0.10.19
[zabbix:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q alex@158.160.34.17"'

[elastic]
10.0.10.10
[elastic:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q alex@158.160.34.17"'

[kibana]
158.160.55.70

[web]
10.0.10.23
10.0.11.27
[web:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q alex@158.160.34.17"'
